/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'account-settings': RouteRecordInfo<'account-settings', '/account-settings', Record<never, never>, Record<never, never>>,
    'admin-photos': RouteRecordInfo<'admin-photos', '/admin/photos', Record<never, never>, Record<never, never>>,
    'admin-upload-photo': RouteRecordInfo<'admin-upload-photo', '/admin/upload-photo', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'cards': RouteRecordInfo<'cards', '/cards', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'form-layouts': RouteRecordInfo<'form-layouts', '/form-layouts', Record<never, never>, Record<never, never>>,
    'icons': RouteRecordInfo<'icons', '/icons', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'tables': RouteRecordInfo<'tables', '/tables', Record<never, never>, Record<never, never>>,
    'typography': RouteRecordInfo<'typography', '/typography', Record<never, never>, Record<never, never>>,
  }
}
