export interface Event {
  id: string
  name: string
  folder_code: string
  start_date: string
  end_date: string
  unit_id: string | null
  outlet_id: string | null
  is_active: boolean
  created_at?: string
  /** Generated by the API from EVENT_PUBLIC_BASE_URL — the link behind the QR. */
  event_url: string
  /** API path to the share QR PNG (no auth, so it works in an <img src>). */
  qr_url: string
  photo_count: number
}

export interface GetEventsResponse {
  data: Event[]
  total: number
  page: number
  limit: number
}
